Repository hufscheer/spectator-server, pull requests merged in 2023-12, with the labels that each got.

#83 [FIX] 임시로 페이징 되지 않도록 수정 및 경기 종료 시 정렬 기준 수정
  src/main/java/com/sports/server/game/infra/GameDynamicRepositoryImpl.java
  src/test/java/com/sports/server/game/acceptance/GameAcceptanceTest.java
  src/test/java/com/sports/server/game/application/GameServiceTest.java
Labels: 🐈 승희, fix

#85 Fix/#84 game cursor paging
  src/main/java/com/sports/server/game/application/GameService.java
  src/main/java/com/sports/server/game/domain/GameDynamicRepository.java
  src/main/java/com/sports/server/game/infra/GameDynamicRepositoryImpl.java
  src/main/java/com/sports/server/game/infra/GamesQueryConditionMapper.java
  src/test/java/com/sports/server/game/acceptance/GameAcceptanceTest.java
  src/test/java/com/sports/server/game/application/GameServiceTest.java
  src/test/resources/game-fixture.sql
Labels: 동규, fix

#89 [CHORE] 프로메테우스 설정 추가
  build.gradle
  src/main/resources/application.yaml
Labels: chore, 동규

#91 [INFRA] 운영 환경에서 로그 파일로 관리 및 실행 시간 로깅
  .github/workflows/cd.yml
  .gitignore
  build.gradle
  src/main/java/com/sports/server/ServerApplication.java
  src/main/java/com/sports/server/common/config/AsyncConfig.java
  src/main/java/com/sports/server/common/log/CorrelationIdFilter.java
  src/main/java/com/sports/server/common/log/LogFilter.java
  src/main/java/com/sports/server/common/log/ThrowableCallable.java
  src/main/java/com/sports/server/common/log/ThrowableRunnable.java
  src/main/java/com/sports/server/common/log/TimeLogAspect.java
  src/main/java/com/sports/server/common/log/TimeLogPointCut.java
  src/main/java/com/sports/server/common/log/TimeLogTemplate.java
  src/main/resources/logback-spring.xml
Labels: infra, 동규
