Repository hufscheer/spectator-server, pull requests merged in 2023-11, with the labels that each got.

#41 [REFACTOR] 제약 조건 수정 및 칼럼 추가
  src/main/java/com/sports/server/comment/application/CommentService.java
  src/main/java/com/sports/server/comment/domain/Comment.java
  src/main/java/com/sports/server/comment/domain/CommentRepository.java
  src/main/java/com/sports/server/comment/dto/request/CommentRequestDto.java
  src/main/java/com/sports/server/game/application/GameService.java
  src/main/java/com/sports/server/game/application/GameTeamService.java
  src/main/java/com/sports/server/game/domain/Game.java
  src/main/java/com/sports/server/game/domain/GameState.java
  src/main/java/com/sports/server/game/domain/GameStatus.java
  src/main/java/com/sports/server/game/domain/GameTeam.java
  src/main/java/com/sports/server/game/domain/GameTeamPlayer.java
  src/main/java/com/sports/server/league/domain/League.java
  src/main/java/com/sports/server/league/domain/LeagueSport.java
  src/main/java/com/sports/server/member/domain/Member.java
  src/main/java/com/sports/server/record/domain/Record.java
  src/main/java/com/sports/server/report/domain/Report.java
  src/main/java/com/sports/server/report/domain/ReportState.java
  src/main/java/com/sports/server/sport/domain/Quarter.java
  src/main/java/com/sports/server/team/domain/Team.java
  src/main/resources/db/migration/V2__update-table.sql
Labels: refactor

#45 [FEAT] 응원하기 개수 확인 기능 구현
  src/main/java/com/sports/server/game/application/GameService.java
  src/main/java/com/sports/server/game/domain/GameTeamRepository.java
  src/main/java/com/sports/server/game/dto/response/GameTeamCheerResponseDto.java
  src/main/java/com/sports/server/game/presentation/GameController.java
Labels: feature, 🐈 승희

#46 [FEAT] 리그 전체 조회 및 리그 스포츠 조회 기능 구현
  build.gradle
  src/main/java/com/sports/server/league/application/LeagueService.java
  src/main/java/com/sports/server/league/domain/League.java
  src/main/java/com/sports/server/league/domain/LeagueRepository.java
  src/main/java/com/sports/server/league/domain/LeagueSport.java
  src/main/java/com/sports/server/league/domain/LeagueSportRepository.java
  src/main/java/com/sports/server/league/dto/response/LeagueResponse.java
  src/main/java/com/sports/server/league/dto/response/LeagueSportResponse.java
  src/main/java/com/sports/server/league/presentation/LeagueController.java
  src/main/java/com/sports/server/sport/domain/Sport.java
  src/test/java/com/sports/server/league/acceptance/LeagueAcceptanceTest.java
  src/test/java/com/sports/server/support/AcceptanceTest.java
  src/test/java/com/sports/server/support/isolation/DatabaseIsolation.java
  src/test/java/com/sports/server/support/isolation/DatabaseIsolationExtension.java
  src/test/java/com/sports/server/support/isolation/DatabaseManager.java
  src/test/resources/league-fixture.sql
Labels: feature, 동규

#49 [FEAT] 응원하기 기능 구현
  src/main/java/com/sports/server/game/application/GameService.java
  src/main/java/com/sports/server/game/application/GameServiceUtils.java
  src/main/java/com/sports/server/game/application/GameTeamService.java
  src/main/java/com/sports/server/game/domain/GameTeamRepository.java
  src/main/java/com/sports/server/game/dto/request/GameTeamCheerRequestDto.java
  src/main/java/com/sports/server/game/exception/GameErrorMessages.java
  src/main/java/com/sports/server/game/presentation/GameController.java
  src/test/java/com/sports/server/game/acceptance/GameTeamAcceptanceTest.java
  src/test/java/com/sports/server/game/application/GameTeamServiceTest.java
  src/test/resources/game-fixture.sql
Labels: feature, 🐈 승희

#56 [FEAT] 경기 상세 조회 구현
  src/main/java/com/sports/server/game/application/GameService.java
  src/main/java/com/sports/server/game/domain/Game.java
  src/main/java/com/sports/server/game/domain/GameTeamRepository.java
  src/main/java/com/sports/server/game/dto/response/GameDetailResponse.java
  src/main/java/com/sports/server/game/dto/response/GameDetailResponseDto.java
  src/main/java/com/sports/server/game/presentation/GameController.java
  src/test/java/com/sports/server/game/acceptance/GameAcceptanceTest.java
  src/test/resources/game-fixture.sql
Labels: feature, 동규

#59 [FEAT] 라인업 조회 기능 추가 및 TeamPlayer 추가
  src/main/java/com/sports/server/game/application/GameTeamPlayerService.java
  src/main/java/com/sports/server/game/domain/GameTeamPlayerRepository.java
  src/main/java/com/sports/server/game/dto/response/GameLineupResponse.java
  src/main/java/com/sports/server/game/presentation/GameController.java
  src/main/java/com/sports/server/team/domain/TeamPlayer.java
  src/main/resources/db/migration/V3__add-team-player.sql
  src/test/java/com/sports/server/game/acceptance/GameTeamPlayerAcceptanceTest.java
  src/test/resources/game-fixture.sql
Labels: feature, 동규, db

#54 [FEAT] 댓글 저장 기능 구현
  build.gradle
  src/main/java/com/sports/server/comment/application/CommentService.java
  src/main/java/com/sports/server/comment/domain/Comment.java
  src/main/java/com/sports/server/comment/domain/CommentEvent.java
  src/main/java/com/sports/server/comment/domain/LanguageFilter.java
  src/main/java/com/sports/server/comment/dto/CommentValidatorMessages.java
  src/main/java/com/sports/server/comment/dto/request/CommentRequestDto.java
  src/main/java/com/sports/server/comment/exception/CommentErrorMessages.java
  src/main/java/com/sports/server/comment/infra/LanguageFilterImpl.java
  src/main/java/com/sports/server/comment/presentation/CommentController.java
  src/test/java/com/sports/server/comment/acceptance/CommentAcceptanceTest.java
  src/test/java/com/sports/server/comment/application/CommentServiceTest.java
  src/test/resources/comment-fixture.sql
Labels: feature, 🐈 승희

#64 [FEAT] 타임라인 조회 기능 구현 및 리그 조회 API 수정
  src/main/java/com/sports/server/league/dto/response/LeagueResponse.java
  src/main/java/com/sports/server/record/application/TimelineService.java
  src/main/java/com/sports/server/record/domain/Record.java
  src/main/java/com/sports/server/record/domain/RecordRepository.java
  src/main/java/com/sports/server/record/dto/response/RecordResponseDto.java
  src/main/java/com/sports/server/record/dto/response/TimelineResponse.java
  src/main/java/com/sports/server/record/presentation/TimelineController.java
  src/main/java/com/sports/server/sport/domain/Quarter.java
  src/main/resources/db/migration/V4__update-records.sql
  src/test/java/com/sports/server/league/acceptance/LeagueAcceptanceTest.java
  src/test/java/com/sports/server/record/acceptance/TimelineAcceptanceTest.java
  src/test/resources/record-fixture.sql
Labels: feature, 동규

#68 [FEAT] 비디오 ID 조회 API 구현 및 게임 상세 조회에 스포츠 이름 추가
  src/main/java/com/sports/server/game/application/GameService.java
  src/main/java/com/sports/server/game/dto/response/GameDetailResponse.java
  src/main/java/com/sports/server/game/dto/response/VideoResponse.java
  src/main/java/com/sports/server/game/presentation/GameController.java
  src/test/java/com/sports/server/game/acceptance/GameAcceptanceTest.java
  src/test/resources/game-fixture.sql
Labels: feature, 동규

#65 [FEAT] 경기 목록 조회
  .gitignore
  build.gradle
  src/main/java/com/sports/server/common/config/QueryDslConfig.java
  src/main/java/com/sports/server/game/application/GameService.java
  src/main/java/com/sports/server/game/application/GameTeamService.java
  src/main/java/com/sports/server/game/domain/GameDynamicRepository.java
  src/main/java/com/sports/server/game/domain/GameRepository.java
  src/main/java/com/sports/server/game/domain/GameState.java
  src/main/java/com/sports/server/game/domain/GameTeamRepository.java
  src/main/java/com/sports/server/game/dto/request/GamesQueryRequestDto.java
  src/main/java/com/sports/server/game/dto/request/PageRequestDto.java
  src/main/java/com/sports/server/game/dto/response/GameDetailResponse.java
  src/main/java/com/sports/server/game/dto/response/GameResponseDto.java
  src/main/java/com/sports/server/game/exception/GameErrorMessages.java
  src/main/java/com/sports/server/game/infra/DynamicBooleanBuilder.java
  src/main/java/com/sports/server/game/infra/GameDynamicRepositoryImpl.java
  src/main/java/com/sports/server/game/presentation/GameController.java
  src/test/java/com/sports/server/game/acceptance/GameAcceptanceTest.java
  src/test/java/com/sports/server/game/application/GameServiceTest.java
  src/test/resources/game-fixture.sql
Labels: feature, 🐈 승희

#71 [FEAT] 댓글 모두 조회 API 구현
  src/main/java/com/sports/server/comment/application/CommentService.java
  src/main/java/com/sports/server/comment/domain/CommentDynamicRepository.java
  src/main/java/com/sports/server/comment/dto/response/CommentResponse.java
  src/main/java/com/sports/server/comment/infra/CommentDynamicRepositoryImpl.java
  src/main/java/com/sports/server/comment/presentation/CommentController.java
  src/main/java/com/sports/server/common/dto/PageRequestDto.java
  src/main/java/com/sports/server/game/application/GameService.java
  src/main/java/com/sports/server/game/domain/GameDynamicRepository.java
  src/main/java/com/sports/server/game/infra/GameDynamicRepositoryImpl.java
  src/main/java/com/sports/server/game/presentation/GameController.java
  src/test/java/com/sports/server/comment/acceptance/CommentAcceptanceTest.java
  src/test/java/com/sports/server/game/application/GameServiceTest.java
  src/test/resources/comment-fixture.sql
Labels: feature, 동규

#72 [FEAT] 댓글 웹소켓 추가
  build.gradle
  src/main/java/com/sports/server/comment/dto/response/CommentResponseDto.java
  src/main/java/com/sports/server/comment/infra/CommentEventHandler.java
  src/main/java/com/sports/server/common/config/WebSocketConfig.java
  src/test/java/com/sports/server/comment/acceptance/CommentAcceptanceTest.java
  src/test/java/com/sports/server/comment/acceptance/CommentEventHandlerTest.java
  src/test/java/com/sports/server/support/AcceptanceTest.java
  src/test/resources/comment-fixture.sql
Labels: feature, 🐈 승희

#74 [FIX] 댓글 조회 순서 로직 수정 #73
  src/main/java/com/sports/server/comment/infra/CommentDynamicRepositoryImpl.java
  src/test/java/com/sports/server/comment/acceptance/CommentAcceptanceTest.java
Labels: bug, 동규, fix

#76 [FEAT] GameTeamId 반환 시에 응답형태에 order 를 함께 반환한다
  src/main/java/com/sports/server/comment/application/CommentService.java
  src/main/java/com/sports/server/comment/dto/response/CommentResponse.java
  src/main/java/com/sports/server/comment/infra/CommentEventHandler.java
  src/main/java/com/sports/server/game/application/GameService.java
  src/main/java/com/sports/server/game/application/GameTeamPlayerService.java
  src/main/java/com/sports/server/game/application/GameTeamService.java
  src/main/java/com/sports/server/game/application/GameTeamServiceUtils.java
  src/main/java/com/sports/server/game/domain/GameRepository.java
  src/main/java/com/sports/server/game/dto/response/GameDetailResponse.java
  src/main/java/com/sports/server/game/dto/response/GameLineupResponse.java
  src/main/java/com/sports/server/game/dto/response/GameResponseDto.java
  src/main/java/com/sports/server/game/dto/response/GameTeamCheerResponseDto.java
  src/test/java/com/sports/server/comment/acceptance/CommentAcceptanceTest.java
  src/test/java/com/sports/server/comment/acceptance/CommentEventHandlerTest.java
  src/test/java/com/sports/server/comment/application/CommentServiceTest.java
  src/test/java/com/sports/server/game/acceptance/GameAcceptanceTest.java
  src/test/java/com/sports/server/game/application/GameServiceTest.java
  src/test/java/com/sports/server/game/application/GameTeamServiceTest.java
Labels: feature, 🐈 승희

#79 [CHORE] cors 허용 origin 외부 설정 파일로 분리
  src/main/java/com/sports/server/common/config/WebConfig.java
  src/main/resources/application-local.yml
Labels: chore, 동규

#81 [FIX] 경기 전체 조회 시 페이징이 올바르지 않게 되는 오류를 해결한다
  src/main/java/com/sports/server/game/infra/GameDynamicRepositoryImpl.java
  src/test/java/com/sports/server/game/application/GameServiceTest.java
Labels: 🐈 승희, fix
