Repository hufscheer/spectator-server, pull requests merged in 2024-03, with the labels that each got.

#120 [DEL] 필요 없는 order 관련 로직 및 필드 삭제
  src/main/java/com/sports/server/query/application/CheerTalkQueryService.java
  src/main/java/com/sports/server/query/application/GameTeamQueryService.java
  src/main/java/com/sports/server/query/application/GameTeamServiceUtils.java
  src/main/java/com/sports/server/query/application/LineupPlayerQueryService.java
  src/main/java/com/sports/server/query/dto/response/CheerTalkResponse.java
  src/main/java/com/sports/server/query/dto/response/GameDetailResponse.java
  src/main/java/com/sports/server/query/dto/response/GameResponseDto.java
  src/main/java/com/sports/server/query/dto/response/GameTeamCheerResponseDto.java
  src/main/java/com/sports/server/query/dto/response/LineupPlayerResponse.java
  src/main/java/com/sports/server/query/presentation/CheerTalkEventHandler.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/query/acceptance/CheerTalkEventHandlerTest.java
  src/test/java/com/sports/server/query/acceptance/CheerTalkQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/acceptance/GameQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/application/CheerTalkQueryServiceTest.java
  src/test/java/com/sports/server/query/application/GameLeagueTeamQueryServiceTest.java
  src/test/java/com/sports/server/query/application/GameQueryServiceTest.java
  src/test/java/com/sports/server/query/application/LineupPlayerQueryServiceTest.java
  src/test/java/com/sports/server/query/presentation/CheerTalkQueryControllerTest.java
  src/test/java/com/sports/server/query/presentation/GameQueryControllerTest.java
Labels: 🐈 승희, del

#122 [FEAT] 타임라인 조회에 필드 추가
  src/main/java/com/sports/server/query/dto/mapper/RecordMapper.java
  src/main/java/com/sports/server/query/dto/response/RecordResponse.java
  src/main/java/com/sports/server/query/dto/response/ReplacementRecordResponse.java
  src/main/java/com/sports/server/query/dto/response/ScoreRecordResponse.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/query/acceptance/TimelineQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/presentation/TimelineQueryControllerTest.java
Labels: feature, 동규

#124 [FIX] 서버 시간 Asia/Seoul로 변경
  src/main/java/com/sports/server/ServerApplication.java
  src/main/resources/logback-spring.xml
Labels: 동규, fix

#126 [FIX] 서버 시간 수정 후 빌드가 실패하는 문제 해결
  .github/workflows/cd.yml
  src/main/java/com/sports/server/query/dto/response/GameResponseDto.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/query/acceptance/GameQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/presentation/GameQueryControllerTest.java
Labels: 동규, fix

#136 [FEAT] lineup_players 와 league_team_players 가 간접 참조하도록 한다
  src/main/java/com/sports/server/command/game/domain/LineupPlayer.java
  src/main/resources/db/migration/V9__update-lineup-players.sql
  src/test/resources/game-fixture.sql
  src/test/resources/record-fixture.sql
Labels: 🐈 승희, add

#140 [FIX] ScoreRecord 조회 시 recorded_at이 아닌 id로 정렬하도록 수정 #139
  src/main/java/com/sports/server/query/repository/ScoreRecordQueryRepository.java
  src/test/java/com/sports/server/query/acceptance/TimelineQueryAcceptanceTest.java
  src/test/resources/record-fixture.sql
Labels: bug, 동규, fix

#142 [FIX] 한 번에 보낼 수 있는 응원 횟수 제한 로직 구현
  src/main/java/com/sports/server/command/game/application/GameTeamService.java
  src/main/java/com/sports/server/command/game/domain/GameTeam.java
  src/test/java/com/sports/server/command/game/application/GameLeagueTeamServiceTest.java
Labels: feature, 🐈 승희

#144 [FIX] 응원 횟수 음수 방지 기능 구현
  src/main/java/com/sports/server/command/game/domain/GameTeam.java
  src/main/java/com/sports/server/common/advice/ControllerExceptionAdvice.java
  src/test/java/com/sports/server/command/game/application/GameLeagueTeamServiceTest.java
Labels: 동규, fix
