Repository hufscheer/spectator-server, pull requests merged in 2024-06, with the labels that each got.

#148 [REFACTOR] 대회팀, 대회팀 선수 가나다 순으로 뜨도록 수정
  src/main/java/com/sports/server/query/application/LeagueQueryService.java
  src/main/java/com/sports/server/query/dto/response/LeagueTeamPlayerResponse.java
  src/main/java/com/sports/server/query/dto/response/LeagueTeamResponse.java
  src/main/java/com/sports/server/query/presentation/LeagueQueryController.java
  src/main/java/com/sports/server/query/repository/LeagueTeamPlayerQueryRepository.java
  src/main/java/com/sports/server/query/repository/LeagueTeamQueryRepository.java
  src/test/java/com/sports/server/query/acceptance/LeagueQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
  src/test/resources/league-fixture.sql
Labels: refactor, 병룡

#152 [FEAT] 리그팀 라운드 별로 조회할 수 있게 쿼리 조건 추가
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/query/application/LeagueQueryService.java
  src/main/java/com/sports/server/query/presentation/LeagueQueryController.java
  src/main/java/com/sports/server/query/repository/LeagueTeamDynamicRepository.java
  src/main/java/com/sports/server/query/repository/LeagueTeamQueryRepository.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/query/acceptance/LeagueQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/acceptance/LeagueTeamQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/application/GameQueryServiceTest.java
  src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
  src/test/resources/game-fixture.sql
Labels: feature, 동규

#155 [REFACTOR] 타임라인 엔티티 재설계
  src/main/java/com/sports/server/command/timeline/domain/GameProgressTimeline.java
  src/main/java/com/sports/server/command/timeline/domain/GameProgressType.java
  src/main/java/com/sports/server/command/timeline/domain/PKTimeline.java
  src/main/java/com/sports/server/command/timeline/domain/ReplacementTimeline.java
  src/main/java/com/sports/server/command/timeline/domain/ScoreTimeline.java
  src/main/java/com/sports/server/command/timeline/domain/Timeline.java
  src/main/resources/db/migration/V10__add_timeline.sql
  src/test/java/com/sports/server/support/isolation/DatabaseManager.java
  src/test/java/com/sports/server/support/isolation/H2TableNameExtractor.java
  src/test/java/com/sports/server/support/isolation/MySqlTableNameExtractor.java
  src/test/java/com/sports/server/support/isolation/TableNameExtractor.java
Labels: refactor, 동규
