Repository hufscheer/spectator-server, pull requests merged in 2024-07, with the labels that each got.

#153 [FEAT] 라인업 변경 사항 반영
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/command/game/application/LineupPlayerService.java
  src/main/java/com/sports/server/command/game/domain/Game.java
  src/main/java/com/sports/server/command/game/domain/GameTeam.java
  src/main/java/com/sports/server/command/game/domain/LineupPlayer.java
  src/main/java/com/sports/server/command/game/domain/LineupPlayerState.java
  src/main/java/com/sports/server/command/game/dto/LineupPlayerStateUpdateRequest.java
  src/main/java/com/sports/server/command/game/exception/LineupErrorMessages.java
  src/main/java/com/sports/server/command/game/presentation/GameController.java
  src/main/java/com/sports/server/query/dto/response/LineupPlayerResponse.java
  src/main/resources/db/migration/V11__update-lineup-players.sql
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/game/acceptance/GameAcceptanceTest.java
  src/test/java/com/sports/server/command/game/acceptance/GameLeagueTeamAcceptanceTest.java
  src/test/java/com/sports/server/command/game/presentation/GameControllerTest.java
  src/test/java/com/sports/server/query/presentation/GameQueryControllerTest.java
  src/test/java/com/sports/server/support/DocumentationTest.java
  src/test/resources/game-fixture.sql
Labels: feature, refactor, 병룡

#150 [FEAT] 사용자 인증, 인가
  build.gradle
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/auth/application/AuthService.java
  src/main/java/com/sports/server/auth/config/SecurityConfig.java
  src/main/java/com/sports/server/auth/dto/LoginRequest.java
  src/main/java/com/sports/server/auth/dto/LoginResponse.java
  src/main/java/com/sports/server/auth/exception/AuthorizationErrorMessages.java
  src/main/java/com/sports/server/auth/exception/DefaultExceptionHandler.java
  src/main/java/com/sports/server/auth/exception/DelegatedAuthenticationEntryPoint.java
  src/main/java/com/sports/server/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/sports/server/auth/presentation/AuthController.java
  src/main/java/com/sports/server/auth/resolver/AuthMemberResolver.java
  src/main/java/com/sports/server/auth/utils/CookieUtil.java
  src/main/java/com/sports/server/auth/utils/JwtUtil.java
  src/main/java/com/sports/server/command/member/domain/Member.java
  src/main/java/com/sports/server/command/member/domain/MemberRepository.java
  src/main/java/com/sports/server/common/config/WebConfig.java
  src/main/java/com/sports/server/common/exception/UnauthorizedException.java
  src/main/resources/application-ci.yml
  src/main/resources/application-local.yml
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/auth/acceptance/AuthAcceptanceTest.java
  src/test/java/com/sports/server/auth/application/AuthServiceTest.java
  src/test/java/com/sports/server/auth/jwt/JwtUtilTest.java
  src/test/java/com/sports/server/auth/presentation/AuthControllerTest.java
  src/test/java/com/sports/server/auth/utils/CookieUtilTest.java
  src/test/java/com/sports/server/command/cheertalk/presentation/CheerTalkControllerTest.java
  src/test/java/com/sports/server/support/DocumentationTest.java
  src/test/resources/member-fixture.sql
Labels: feature, 🐈 승희

#160 [FEAT] 리그팀 생성
  build.gradle
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/auth/config/SecurityConfig.java
  src/main/java/com/sports/server/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/sports/server/command/game/domain/GameTeam.java
  src/main/java/com/sports/server/command/league/domain/League.java
  src/main/java/com/sports/server/command/leagueteam/LeagueTeam.java
  src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
  src/main/java/com/sports/server/command/leagueteam/domain/LeagueTeam.java
  src/main/java/com/sports/server/command/leagueteam/domain/LeagueTeamPlayer.java
  src/main/java/com/sports/server/command/leagueteam/domain/LeagueTeamRepository.java
  src/main/java/com/sports/server/command/leagueteam/dto/LeagueTeamRegisterRequest.java
  src/main/java/com/sports/server/command/leagueteam/presentation/LeagueTeamController.java
  src/main/java/com/sports/server/common/application/PresignedUrlGenerator.java
  src/main/java/com/sports/server/common/config/AwsConfig.java
  src/main/java/com/sports/server/common/presentation/S3Controller.java
  src/main/java/com/sports/server/query/dto/mapper/RecordMapper.java
  src/main/java/com/sports/server/query/dto/response/LeagueTeamPlayerResponse.java
  src/main/java/com/sports/server/query/dto/response/LeagueTeamResponse.java
  src/main/java/com/sports/server/query/dto/response/RecordResponse.java
  src/main/java/com/sports/server/query/repository/LeagueTeamDynamicRepository.java
  src/main/java/com/sports/server/query/repository/LeagueTeamPlayerQueryRepository.java
  src/main/resources/application-ci.yml
  src/main/resources/application-local.yml
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/auth/presentation/AuthControllerTest.java
  src/test/java/com/sports/server/command/leagueteam/acceptance/LeagueTeamAcceptanceTest.java
  src/test/java/com/sports/server/command/leagueteam/application/LeagueTeamServiceTest.java
  src/test/java/com/sports/server/command/leagueteam/presentation/LeagueTeamControllerTest.java
  src/test/java/com/sports/server/support/AcceptanceTest.java
  src/test/java/com/sports/server/support/DocumentationTest.java
  src/test/resources/league-fixture.sql
Labels: feature, 🐈 승희

#162 [FEAT] 득점, 교체 타임라인 생성 도메인 로직 구현
  .gitignore
  build.gradle
  src/main/java/com/sports/server/command/game/domain/Game.java
  src/main/java/com/sports/server/command/game/domain/GameTeam.java
  src/main/java/com/sports/server/command/game/domain/LineupPlayer.java
  src/main/java/com/sports/server/command/timeline/domain/ReplacementTimeline.java
  src/main/java/com/sports/server/command/timeline/domain/ScoreTimeline.java
  src/main/java/com/sports/server/command/timeline/domain/Timeline.java
  src/test/java/com/sports/server/command/game/domain/GameTest.java
  src/test/java/com/sports/server/command/timeline/domain/ReplacementTimelineTest.java
  src/test/java/com/sports/server/command/timeline/domain/ScoreTimelineTest.java
  src/test/java/com/sports/server/support/fixture/FixtureMonkeyUtils.java
Labels: feature

#164 대회 생성 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/auth/config/SecurityConfig.java
  src/main/java/com/sports/server/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/sports/server/command/league/application/LeagueService.java
  src/main/java/com/sports/server/command/league/domain/League.java
  src/main/java/com/sports/server/command/league/domain/LeagueRepository.java
  src/main/java/com/sports/server/command/league/domain/LeagueRound.java
  src/main/java/com/sports/server/command/league/domain/LeagueRoundConverter.java
  src/main/java/com/sports/server/command/league/dto/LeagueRequestDto.java
  src/main/java/com/sports/server/command/league/exception/LeagueErrorMessages.java
  src/main/java/com/sports/server/command/league/presentation/LeagueController.java
  src/main/java/com/sports/server/query/dto/response/LeagueDetailResponse.java
  src/main/java/com/sports/server/query/dto/response/LeagueResponse.java
  src/main/resources/db/migration/V13__update-league.sql
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/league/acceptance/LeagueAcceptanceTest.java
  src/test/java/com/sports/server/command/league/domain/LeagueTest.java
  src/test/java/com/sports/server/command/league/presentation/LeagueControllerTest.java
  src/test/java/com/sports/server/query/acceptance/LeagueQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
  src/test/java/com/sports/server/support/DocumentationTest.java
  src/test/java/com/sports/server/support/fixture/FixtureMonkeyUtils.java
  src/test/resources/game-fixture.sql
  src/test/resources/league-fixture.sql
Labels: feature, refactor, test, 병룡

#167 [FEAT] 득점, 교체 타임라인 생성 api 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/auth/config/SecurityConfig.java
  src/main/java/com/sports/server/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/sports/server/command/game/domain/Game.java
  src/main/java/com/sports/server/command/game/domain/LineupPlayer.java
  src/main/java/com/sports/server/command/timeline/TimelineRequest.java
  src/main/java/com/sports/server/command/timeline/application/TimelineService.java
  src/main/java/com/sports/server/command/timeline/domain/TimelineRepository.java
  src/main/java/com/sports/server/command/timeline/presentation/TimelineController.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/game/domain/GameTest.java
  src/test/java/com/sports/server/command/leagueteam/acceptance/LeagueTeamAcceptanceTest.java
  src/test/java/com/sports/server/command/timeline/TimelineFixtureRepository.java
  src/test/java/com/sports/server/command/timeline/acceptance/TimelineAcceptanceTest.java
  src/test/java/com/sports/server/command/timeline/application/TimelineServiceTest.java
  src/test/java/com/sports/server/command/timeline/presentation/TimelineControllerTest.java
  src/test/java/com/sports/server/query/acceptance/TimelineQueryAcceptanceTest.java
  src/test/java/com/sports/server/support/AcceptanceTest.java
  src/test/java/com/sports/server/support/DocumentationTest.java
  src/test/resources/timeline-fixture.sql
Labels: feature

#172 [FIX] 만료된 토큰으로 로그인 요청 버그 해결
  src/main/java/com/sports/server/auth/filter/JwtAuthorizationFilter.java
  src/test/java/com/sports/server/auth/acceptance/AuthAcceptanceTest.java
Labels: fix

#165 [FEAT] 리그팀 수정 기능 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/auth/config/SecurityConfig.java
  src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
  src/main/java/com/sports/server/command/leagueteam/domain/LeagueTeam.java
  src/main/java/com/sports/server/command/leagueteam/domain/LeagueTeamPlayer.java
  src/main/java/com/sports/server/command/leagueteam/domain/LeagueTeamPlayerRepository.java
  src/main/java/com/sports/server/command/leagueteam/domain/LeagueTeamRepository.java
  src/main/java/com/sports/server/command/leagueteam/domain/LogoImageDeletedEvent.java
  src/main/java/com/sports/server/command/leagueteam/dto/LeagueTeamPlayerRequest.java
  src/main/java/com/sports/server/command/leagueteam/dto/LeagueTeamRegisterRequest.java
  src/main/java/com/sports/server/command/leagueteam/dto/LeagueTeamRequest.java
  src/main/java/com/sports/server/command/leagueteam/infrastructure/LogoImageEventHandler.java
  src/main/java/com/sports/server/command/leagueteam/presentation/LeagueTeamController.java
  src/main/java/com/sports/server/common/application/S3Service.java
  src/main/java/com/sports/server/common/presentation/S3Controller.java
  src/main/resources/application-ci.yml
  src/main/resources/application-local.yml
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/leagueteam/acceptance/LeagueTeamAcceptanceTest.java
  src/test/java/com/sports/server/command/leagueteam/application/LeagueTeamServiceTest.java
  src/test/java/com/sports/server/command/leagueteam/presentation/LeagueTeamControllerTest.java
  src/test/resources/league-fixture.sql
Labels: feature, 🐈 승희

#177 [FEAT] 리그팀 삭제
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/auth/config/SecurityConfig.java
  src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
  src/main/java/com/sports/server/command/leagueteam/domain/LeagueTeam.java
  src/main/java/com/sports/server/command/leagueteam/domain/LeagueTeamPlayerFixtureRepository.java
  src/main/java/com/sports/server/command/leagueteam/domain/LeagueTeamRepository.java
  src/main/java/com/sports/server/command/leagueteam/presentation/LeagueTeamController.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/leagueteam/acceptance/LeagueTeamAcceptanceTest.java
  src/test/java/com/sports/server/command/leagueteam/application/LeagueTeamServiceTest.java
  src/test/java/com/sports/server/command/leagueteam/presentation/LeagueTeamControllerTest.java
Labels: feature, 🐈 승희
