Repository hufscheer/spectator-server, pull requests merged in 2024-08, with the labels that each got.

#175 [FEAT] 타임라인 삭제 기능 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/command/game/domain/Game.java
  src/main/java/com/sports/server/command/game/domain/GameTeam.java
  src/main/java/com/sports/server/command/timeline/TimelineRequest.java
  src/main/java/com/sports/server/command/timeline/application/TimelineMapper.java
  src/main/java/com/sports/server/command/timeline/application/TimelineService.java
  src/main/java/com/sports/server/command/timeline/domain/GameProgressTimeline.java
  src/main/java/com/sports/server/command/timeline/domain/PKTimeline.java
  src/main/java/com/sports/server/command/timeline/domain/ReplacementTimeline.java
  src/main/java/com/sports/server/command/timeline/domain/ScoreTimeline.java
  src/main/java/com/sports/server/command/timeline/domain/Timeline.java
  src/main/java/com/sports/server/command/timeline/domain/TimelineRepository.java
  src/main/java/com/sports/server/command/timeline/dto/TimelineRequest.java
  src/main/java/com/sports/server/command/timeline/presentation/TimelineController.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/game/domain/GameTest.java
  src/test/java/com/sports/server/command/timeline/acceptance/TimelineAcceptanceTest.java
  src/test/java/com/sports/server/command/timeline/application/TimelineServiceTest.java
  src/test/java/com/sports/server/command/timeline/presentation/TimelineControllerTest.java
Labels: feature

#180 [FEAT] 멤버 정보 조회 기능 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/auth/config/SecurityConfig.java
  src/main/java/com/sports/server/command/member/domain/MemberRepository.java
  src/main/java/com/sports/server/command/organization/domain/Organization.java
  src/main/java/com/sports/server/query/application/MemberQueryService.java
  src/main/java/com/sports/server/query/dto/response/MemberResponse.java
  src/main/java/com/sports/server/query/presentation/MemberQueryController.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/query/acceptance/MemberQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/application/MemberQueryServiceTest.java
  src/test/java/com/sports/server/query/presentation/MemberQueryControllerTest.java
  src/test/java/com/sports/server/support/DocumentationTest.java
Labels: feature, 🐈 승희

#179 [HOTFIX] Game 의 round 정보 Integer 에서 Enum 으로 변경
  src/main/java/com/sports/server/command/game/domain/Game.java
  src/main/java/com/sports/server/command/league/domain/League.java
  src/main/java/com/sports/server/command/league/domain/LeagueRound.java
  src/main/java/com/sports/server/command/league/domain/LeagueRoundConverter.java
  src/main/java/com/sports/server/command/league/domain/Round.java
  src/main/java/com/sports/server/command/league/domain/RoundConverter.java
  src/main/java/com/sports/server/command/league/dto/LeagueRequestDto.java
  src/main/java/com/sports/server/query/application/LeagueQueryService.java
  src/main/java/com/sports/server/query/dto/request/GamesQueryRequestDto.java
  src/main/java/com/sports/server/query/dto/response/GameResponseDto.java
  src/main/java/com/sports/server/query/presentation/LeagueQueryController.java
  src/main/java/com/sports/server/query/repository/GamesQueryConditionMapper.java
  src/main/java/com/sports/server/query/repository/LeagueTeamDynamicRepository.java
  src/main/resources/db/migration/V14__update-game.sql
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/query/acceptance/GameQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/acceptance/LeagueTeamQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/application/GameQueryServiceTest.java
  src/test/java/com/sports/server/query/presentation/GameQueryControllerTest.java
  src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
  src/test/java/com/sports/server/support/fixture/FixtureMonkeyUtils.java
  src/test/resources/game-fixture.sql
  src/test/resources/timeline-fixture.sql
Labels: 🐈 승희, refactor, fix

#182 [MIGRATION] Record -> Timeline 마이그레이션
  src/main/java/com/sports/server/command/timeline/TimelineMigration.java
  src/test/java/com/sports/server/command/timeline/TimelineMigrationTest.java
  src/test/resources/record-migration-fixture.sql
Labels: 동규, db

#188 [FEAT] 리그팀에 인원수 표기하도록 수정
  src/main/java/com/sports/server/query/dto/response/LeagueTeamResponse.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/query/application/LeagueQueryServiceTest.java
  src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
Labels: feature, 🐈 승희

#191 [FEAT] 리그팀 상세 조회
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/query/application/LeagueQueryService.java
  src/main/java/com/sports/server/query/dto/response/LeagueTeamDetailResponse.java
  src/main/java/com/sports/server/query/presentation/LeagueQueryController.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/query/acceptance/LeagueQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/application/LeagueQueryServiceTest.java
  src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
Labels: feature, 🐈 승희

#190 [FEAT] 리그 삭제
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/auth/config/SecurityConfig.java
  src/main/java/com/sports/server/command/league/application/LeagueService.java
  src/main/java/com/sports/server/command/league/domain/League.java
  src/main/java/com/sports/server/command/league/domain/LeagueRepository.java
  src/main/java/com/sports/server/command/league/presentation/LeagueController.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/league/acceptance/LeagueAcceptanceTest.java
  src/test/java/com/sports/server/command/league/application/LeagueServiceTest.java
  src/test/java/com/sports/server/command/league/domain/LeagueTest.java
  src/test/java/com/sports/server/command/league/presentation/LeagueControllerTest.java
Labels: feature, 🐈 승희

#205 [MIGRATION] Record 기반 레거시 삭제
  src/main/java/com/sports/server/command/record/domain/Record.java
  src/main/java/com/sports/server/command/record/domain/RecordType.java
  src/main/java/com/sports/server/command/record/domain/ReplacementRecord.java
  src/main/java/com/sports/server/command/record/domain/ScoreRecord.java
  src/main/java/com/sports/server/command/timeline/TimelineMigration.java
  src/main/java/com/sports/server/query/application/TimelineQueryService.java
  src/main/java/com/sports/server/query/application/timeline/RecordQueryService.java
  src/main/java/com/sports/server/query/application/timeline/ReplacementRecordQueryService.java
  src/main/java/com/sports/server/query/application/timeline/ScoreHistory.java
  src/main/java/com/sports/server/query/application/timeline/ScoreRecordQueryService.java
  src/main/java/com/sports/server/query/application/timeline/ScoreSnapshot.java
  src/main/java/com/sports/server/query/dto/mapper/RecordMapper.java
  src/main/java/com/sports/server/query/presentation/TimelineQueryController.java
  src/main/java/com/sports/server/query/repository/ReplacementRecordQueryRepository.java
  src/main/java/com/sports/server/query/repository/ScoreRecordQueryRepository.java
  src/main/resources/db/migration/V16__drop-record.sql
  src/test/java/com/sports/server/command/timeline/TimelineMigrationTest.java
  src/test/java/com/sports/server/query/acceptance/TimelineQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/presentation/TimelineQueryControllerTest.java
  src/test/java/com/sports/server/support/DocumentationTest.java
  src/test/resources/record-migration-fixture.sql
Labels: 동규, migration

#193 [FEAT] 대회 수정
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/auth/config/SecurityConfig.java
  src/main/java/com/sports/server/command/league/application/LeagueService.java
  src/main/java/com/sports/server/command/league/domain/League.java
  src/main/java/com/sports/server/command/league/dto/LeagueRequestDto.java
  src/main/java/com/sports/server/command/league/presentation/LeagueController.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/league/acceptance/LeagueAcceptanceTest.java
  src/test/java/com/sports/server/command/league/domain/LeagueTest.java
  src/test/java/com/sports/server/command/league/presentation/LeagueControllerTest.java
  src/test/java/com/sports/server/command/leagueteam/acceptance/LeagueTeamAcceptanceTest.java
  src/test/java/com/sports/server/command/timeline/acceptance/TimelineAcceptanceTest.java
  src/test/java/com/sports/server/support/AcceptanceTest.java
Labels: feature, 병룡

#187 [FEAT] 게임 등록 기능 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/auth/config/SecurityConfig.java
  src/main/java/com/sports/server/command/game/application/GameService.java
  src/main/java/com/sports/server/command/game/domain/Game.java
  src/main/java/com/sports/server/command/game/domain/GameRepository.java
  src/main/java/com/sports/server/command/game/domain/GameTeam.java
  src/main/java/com/sports/server/command/game/domain/LineupPlayer.java
  src/main/java/com/sports/server/command/game/dto/GameRequestDto.java
  src/main/java/com/sports/server/command/game/presentation/GameController.java
  src/main/java/com/sports/server/command/leagueteam/domain/LeagueTeamPlayerFixtureRepository.java
  src/main/java/com/sports/server/command/sport/domain/SportRepository.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/game/acceptance/GameAcceptanceTest.java
  src/test/java/com/sports/server/command/game/application/GameServiceTest.java
  src/test/java/com/sports/server/command/game/presentation/GameControllerTest.java
  src/test/java/com/sports/server/command/leagueteam/application/LeagueTeamServiceTest.java
  src/test/java/com/sports/server/query/acceptance/SportQueryAcceptanceTest.java
  src/test/java/com/sports/server/support/DocumentationTest.java
  src/test/java/com/sports/server/support/fixture/GameFixtureRepository.java
  src/test/java/com/sports/server/support/fixture/GameTeamFixtureRepository.java
  src/test/java/com/sports/server/support/fixture/LeagueTeamPlayerFixtureRepository.java
  src/test/resources/game-fixture.sql
Labels: feature, 🐈 승희
