Repository hufscheer/spectator-server, pull requests merged in 2024-09, with the labels that each got.

#202 [FEAT] 리그에 해당하는 경기 전체 조회
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/query/application/LeagueQueryService.java
  src/main/java/com/sports/server/query/dto/response/LeagueResponseWithGames.java
  src/main/java/com/sports/server/query/presentation/LeagueQueryController.java
  src/main/java/com/sports/server/query/repository/GameQueryRepository.java
  src/main/java/com/sports/server/query/repository/LeagueQueryRepository.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/query/acceptance/LeagueQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/application/LeagueQueryServiceTest.java
  src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
  src/test/resources/league-fixture.sql
Labels: feature, 🐈 승희

#211 [FEAT] 주장 등록 및 취소 기능 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/command/game/application/LineupPlayerService.java
  src/main/java/com/sports/server/command/game/domain/Game.java
  src/main/java/com/sports/server/command/game/domain/GameTeam.java
  src/main/java/com/sports/server/command/game/domain/LineupPlayer.java
  src/main/java/com/sports/server/command/game/presentation/GameController.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/game/acceptance/GameAcceptanceTest.java
  src/test/java/com/sports/server/command/game/application/LineupPlayerServiceTest.java
  src/test/java/com/sports/server/command/game/domain/GameTeamTest.java
  src/test/java/com/sports/server/command/game/domain/GameTest.java
  src/test/java/com/sports/server/command/game/presentation/GameControllerTest.java
  src/test/java/com/sports/server/query/acceptance/GameQueryAcceptanceTest.java
  src/test/resources/game-fixture.sql
Labels: feature, 🐈 승희

#214 [FEAT] 출전 선수 정보 변경
  src/main/java/com/sports/server/command/game/domain/LineupPlayer.java
  src/main/java/com/sports/server/command/timeline/domain/ReplacementTimeline.java
  src/main/resources/db/migration/V17__update-lineup-players.sql
  src/test/java/com/sports/server/command/timeline/TimelineFixtureRepository.java
  src/test/java/com/sports/server/command/timeline/application/TimelineServiceTest.java
  src/test/resources/game-fixture.sql
  src/test/resources/timeline-fixture.sql
Labels: feature, 🐈 승희

#216 [FEAT] 출전 선수 조회 기능 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/query/application/LineupPlayerQueryService.java
  src/main/java/com/sports/server/query/presentation/GameQueryController.java
  src/main/java/com/sports/server/query/repository/LineupPlayerQueryRepository.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/query/acceptance/GameQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/application/LineupPlayerQueryServiceTest.java
  src/test/java/com/sports/server/query/presentation/GameQueryControllerTest.java
  src/test/resources/game-fixture.sql
Labels: feature, 🐈 승희

#209 [FEAT] 게임 진행 상태 변경 타임라인 기능 추가
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/command/timeline/application/TimelineService.java
  src/main/java/com/sports/server/command/timeline/domain/GameProgressTimeline.java
  src/main/java/com/sports/server/command/timeline/domain/PKTimeline.java
  src/main/java/com/sports/server/command/timeline/domain/ReplacementTimeline.java
  src/main/java/com/sports/server/command/timeline/domain/ScoreTimeline.java
  src/main/java/com/sports/server/command/timeline/domain/Timeline.java
  src/main/java/com/sports/server/command/timeline/domain/TimelineType.java
  src/main/java/com/sports/server/command/timeline/dto/TimelineRequest.java
  src/main/java/com/sports/server/command/timeline/mapper/TimelineMapper.java
  src/main/java/com/sports/server/command/timeline/mapper/TimelineSupplier.java
  src/main/java/com/sports/server/command/timeline/presentation/TimelineController.java
  src/main/java/com/sports/server/query/dto/response/ProgressRecordResponse.java
  src/main/java/com/sports/server/query/dto/response/RecordResponse.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/timeline/acceptance/TimelineAcceptanceTest.java
  src/test/java/com/sports/server/command/timeline/application/TimelineServiceTest.java
  src/test/java/com/sports/server/command/timeline/domain/ScoreTimelineTest.java
  src/test/java/com/sports/server/command/timeline/presentation/TimelineControllerTest.java
  src/test/java/com/sports/server/query/acceptance/TimelineQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/presentation/TimelineQueryControllerTest.java
  src/test/resources/timeline-fixture.sql
Labels: feature, 동규

#225 [REFACTOR] 리그 생성 시 자동으로 Organization 등록되도록 수정
  src/main/java/com/sports/server/command/league/application/LeagueService.java
  src/main/java/com/sports/server/command/league/domain/Round.java
  src/main/java/com/sports/server/command/league/dto/LeagueRequestDto.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/league/acceptance/LeagueAcceptanceTest.java
  src/test/java/com/sports/server/command/league/presentation/LeagueControllerTest.java
Labels: refactor, 정아

#221 [FEAT] 신고된 리그의 응원톡 전체 조회
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/auth/config/SecurityConfig.java
  src/main/java/com/sports/server/query/application/CheerTalkQueryService.java
  src/main/java/com/sports/server/query/dto/response/CheerTalkResponse.java
  src/main/java/com/sports/server/query/presentation/CheerTalkEventHandler.java
  src/main/java/com/sports/server/query/presentation/CheerTalkQueryController.java
  src/main/java/com/sports/server/query/repository/CheerTalkDynamicRepository.java
  src/main/java/com/sports/server/query/repository/CheerTalkDynamicRepositoryImpl.java
  src/main/java/com/sports/server/query/repository/GameQueryRepository.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/query/acceptance/CheerTalkEventHandlerTest.java
  src/test/java/com/sports/server/query/acceptance/CheerTalkQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/application/CheerTalkQueryServiceTest.java
  src/test/java/com/sports/server/query/presentation/CheerTalkQueryControllerTest.java
  src/test/resources/cheer-talk-fixture.sql
Labels: feature, 🐈 승희

#228 [FEAT] 신고 시 욕설 확인 기능 구현
  src/main/java/com/sports/server/command/cheertalk/domain/CheerTalk.java
  src/main/java/com/sports/server/command/report/application/ReportProcessor.java
  src/main/java/com/sports/server/command/report/domain/Report.java
  src/main/java/com/sports/server/command/report/infrastructure/ReportEventHandler.java
  src/main/java/com/sports/server/common/application/TextFileProcessor.java
  src/main/resources/static/extra_bad_words.txt
  src/test/java/com/sports/server/command/report/acceptance/ReportAcceptanceTest.java
  src/test/java/com/sports/server/command/report/application/ReportProcessorTest.java
  src/test/java/com/sports/server/command/report/infrastructure/ReportEventHandlerTest.java
  src/test/java/com/sports/server/support/AcceptanceTest.java
  src/test/java/com/sports/server/support/ServiceTest.java
Labels: feature, 🐈 승희

#213 [FEAT] 게임 정보 수정 기능 추가
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/auth/config/SecurityConfig.java
  src/main/java/com/sports/server/command/game/application/GameService.java
  src/main/java/com/sports/server/command/game/domain/Game.java
  src/main/java/com/sports/server/command/game/dto/GameRequestDto.java
  src/main/java/com/sports/server/command/game/presentation/GameController.java
  src/main/java/com/sports/server/query/dto/response/GameDetailResponse.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/game/acceptance/GameAcceptanceTest.java
  src/test/java/com/sports/server/command/game/application/GameServiceTest.java
  src/test/java/com/sports/server/command/game/presentation/GameControllerTest.java
  src/test/java/com/sports/server/query/presentation/GameQueryControllerTest.java
Labels: feature, 정아

#226 [FEAT] 매니저가 관리하는 리그 전체 조회 기능 구현(대회 관리 페이지)
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/command/league/domain/Round.java
  src/main/java/com/sports/server/command/league/dto/LeagueRequestDto.java
  src/main/java/com/sports/server/query/application/LeagueQueryService.java
  src/main/java/com/sports/server/query/dto/response/LeagueResponseToManage.java
  src/main/java/com/sports/server/query/presentation/LeagueQueryController.java
  src/main/java/com/sports/server/query/repository/LeagueQueryRepository.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/query/acceptance/LeagueQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/application/LeagueQueryServiceTest.java
  src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
  src/test/resources/league-fixture.sql
Labels: feature, 정아

#232 [FEAT] 응원톡 관리 화면에서의 응원톡 전체 조회
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/auth/config/SecurityConfig.java
  src/main/java/com/sports/server/command/game/application/GameService.java
  src/main/java/com/sports/server/command/game/domain/Game.java
  src/main/java/com/sports/server/command/league/domain/League.java
  src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
  src/main/java/com/sports/server/command/timeline/application/TimelineService.java
  src/main/java/com/sports/server/common/application/PermissionValidator.java
  src/main/java/com/sports/server/common/domain/ManagedEntity.java
  src/main/java/com/sports/server/query/application/CheerTalkQueryService.java
  src/main/java/com/sports/server/query/dto/response/CheerTalkResponse.java
  src/main/java/com/sports/server/query/presentation/CheerTalkQueryController.java
  src/main/java/com/sports/server/query/repository/CheerTalkDynamicRepository.java
  src/main/java/com/sports/server/query/repository/CheerTalkDynamicRepositoryImpl.java
  src/main/java/com/sports/server/query/repository/GameQueryRepository.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/league/domain/LeagueTest.java
  src/test/java/com/sports/server/query/acceptance/CheerTalkQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/application/CheerTalkQueryServiceTest.java
  src/test/java/com/sports/server/query/presentation/CheerTalkQueryControllerTest.java
Labels: feature, 🐈 승희

#238 [FEAT] 신고된 응원톡 가리기/가리기 해제 기능
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/auth/config/SecurityConfig.java
  src/main/java/com/sports/server/command/cheertalk/application/CheerTalkService.java
  src/main/java/com/sports/server/command/cheertalk/domain/CheerTalk.java
  src/main/java/com/sports/server/command/cheertalk/presentation/CheerTalkController.java
  src/main/java/com/sports/server/command/report/application/ReportProcessor.java
  src/main/java/com/sports/server/command/report/domain/Report.java
  src/main/java/com/sports/server/command/report/exception/ReportErrorMessage.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/cheertalk/acceptance/CheerTalkAcceptanceTest.java
  src/test/java/com/sports/server/command/cheertalk/application/CheerTalkServiceTest.java
  src/test/java/com/sports/server/command/cheertalk/presentation/CheerTalkControllerTest.java
  src/test/java/com/sports/server/command/game/presentation/GameControllerTest.java
  src/test/java/com/sports/server/command/league/presentation/LeagueControllerTest.java
  src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
  src/test/resources/cheer-talk-fixture.sql
Labels: feature, 정아

#241 [FEAT] 응원톡 신고 무효처리 기능
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/command/report/application/ReportService.java
  src/main/java/com/sports/server/command/report/domain/ReportRepository.java
  src/main/java/com/sports/server/command/report/presentation/ReportController.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/report/acceptance/ReportAcceptanceTest.java
  src/test/java/com/sports/server/command/report/application/ReportServiceTest.java
  src/test/java/com/sports/server/command/report/presentation/ReportControllerTest.java
  src/test/resources/report-fixture.sql
Labels: feature, 정아

#245 [FIX] 리그팀 수정 시 발생하는 오류 해결
  src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
  src/main/java/com/sports/server/command/leagueteam/domain/LeagueTeam.java
  src/main/java/com/sports/server/command/leagueteam/domain/LeagueTeamPlayerRepository.java
  src/main/java/com/sports/server/common/application/S3Service.java
  src/test/java/com/sports/server/command/leagueteam/acceptance/LeagueTeamAcceptanceTest.java
  src/test/java/com/sports/server/command/leagueteam/application/LeagueTeamServiceTest.java
Labels: fix, 정아

#247 [FIX] 게임 관련 권한 확인 제대로 되지 않던 문제 해결
  src/main/java/com/sports/server/command/game/domain/Game.java
  src/test/java/com/sports/server/command/timeline/application/TimelineServiceTest.java
  src/test/resources/timeline-fixture.sql
Labels: fix, 정아

#237 [FEAT] 게임 진행 타임라인 내부 로직 구현
  src/main/java/com/sports/server/command/game/domain/Game.java
  src/main/java/com/sports/server/command/game/domain/GameState.java
  src/main/java/com/sports/server/command/sport/domain/Quarter.java
  src/main/java/com/sports/server/command/sport/domain/Sport.java
  src/main/java/com/sports/server/command/timeline/domain/GameProgressTimeline.java
  src/main/java/com/sports/server/query/application/TimelineQueryService.java
  src/main/resources/db/migration/V19__add_quarter_order.sql
  src/test/java/com/sports/server/command/timeline/application/TimelineServiceTest.java
  src/test/java/com/sports/server/command/timeline/domain/GameProgressTimelineTest.java
  src/test/resources/timeline-fixture.sql
Labels: feature

#251 [FEAT] 게임에 승부차기 여부 저장 기능 구현
  src/main/java/com/sports/server/command/game/domain/Game.java
  src/main/java/com/sports/server/command/timeline/domain/GameProgressTimeline.java
  src/main/java/com/sports/server/query/dto/response/GameDetailResponse.java
  src/main/java/com/sports/server/query/dto/response/GameResponseDto.java
  src/main/java/com/sports/server/query/dto/response/LeagueResponseWithGames.java
  src/main/resources/db/migration/V20__update-game.sql
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/timeline/domain/GameProgressTimelineTest.java
  src/test/java/com/sports/server/query/acceptance/GameQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/presentation/GameQueryControllerTest.java
  src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
  src/test/resources/game-fixture.sql
Labels: feature, 🐈 승희

#248 [FEAT] 타임라인 조회에 승부차기 추가
  src/main/java/com/sports/server/query/application/TimelineQueryService.java
  src/main/java/com/sports/server/query/dto/response/PkRecordResponse.java
  src/main/java/com/sports/server/query/dto/response/RecordResponse.java
  src/main/java/com/sports/server/query/repository/TimelineQueryRepository.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/timeline/application/TimelineServiceTest.java
  src/test/java/com/sports/server/query/acceptance/TimelineQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/presentation/TimelineQueryControllerTest.java
  src/test/resources/timeline-fixture.sql
Labels: feature, 🐈 승희

#255 [DOCS] 누락된 주장 등록 및 해제 문서화 #254
  src/docs/asciidoc/api.adoc
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/game/presentation/GameControllerTest.java
Labels: documentation, 🐈 승희

#256 [HOTFIX] 리그의 게임 조회에서 발생하는 오류 수정
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/command/game/domain/Game.java
  src/main/java/com/sports/server/command/game/dto/GameRequestDto.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/query/presentation/CheerTalkQueryControllerTest.java
Labels: 🐈 승희, 💥 hotfix

#257 [REFACTOR] 게임 등록 시 ID 반환하도록 수정
  src/main/java/com/sports/server/command/game/application/GameService.java
  src/main/java/com/sports/server/command/game/presentation/GameController.java
  src/test/java/com/sports/server/command/game/presentation/GameControllerTest.java
Labels: 🐈 승희, refactor

#235 [FEAT] 가려진 응원톡 전체 조회하기
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/auth/config/SecurityConfig.java
  src/main/java/com/sports/server/query/application/CheerTalkQueryService.java
  src/main/java/com/sports/server/query/dto/response/CheerTalkResponse.java
  src/main/java/com/sports/server/query/presentation/CheerTalkQueryController.java
  src/main/java/com/sports/server/query/repository/CheerTalkDynamicRepository.java
  src/main/java/com/sports/server/query/repository/CheerTalkDynamicRepositoryImpl.java
  src/test/java/com/sports/server/command/cheertalk/acceptance/CheerTalkAcceptanceTest.java
  src/test/java/com/sports/server/query/acceptance/CheerTalkQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/application/CheerTalkQueryServiceTest.java
  src/test/java/com/sports/server/query/presentation/CheerTalkQueryControllerTest.java
  src/test/resources/cheer-talk-fixture.sql
Labels: feature, 병룡

#263 [FEAT] /leagues/manager 에 승부차기 성적 반환 안되는 오류 반영
  src/main/java/com/sports/server/query/application/LeagueQueryService.java
  src/main/java/com/sports/server/query/dto/response/LeagueResponseWithInProgressGames.java
  src/main/java/com/sports/server/query/repository/LeagueQueryRepository.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
Labels: feature, 🐈 승희

#259 [FIX] 주장으로 등록된 후보를 선발로 변경 시 주장 해제되도록 수정
  src/main/java/com/sports/server/auth/config/SecurityConfig.java
  src/main/java/com/sports/server/command/game/application/LineupPlayerService.java
  src/main/java/com/sports/server/command/game/domain/Game.java
  src/main/java/com/sports/server/command/game/domain/GameTeam.java
  src/main/java/com/sports/server/command/game/domain/LineupPlayer.java
  src/main/java/com/sports/server/command/game/presentation/GameController.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/game/acceptance/GameAcceptanceTest.java
  src/test/java/com/sports/server/command/game/application/LineupPlayerServiceTest.java
  src/test/java/com/sports/server/command/game/domain/GameTest.java
  src/test/java/com/sports/server/command/game/presentation/GameControllerTest.java
  src/test/resources/game-fixture.sql
Labels: fix, 정아

#261 [FEAT] 게임 삭제
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/auth/config/SecurityConfig.java
  src/main/java/com/sports/server/command/game/application/GameService.java
  src/main/java/com/sports/server/command/game/domain/GameRepository.java
  src/main/java/com/sports/server/command/game/presentation/GameController.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/game/acceptance/GameAcceptanceTest.java
  src/test/java/com/sports/server/command/game/application/GameServiceTest.java
  src/test/java/com/sports/server/command/game/presentation/GameControllerTest.java
Labels: feature, 정아
