Repository hufscheer/spectator-server, pull requests merged in 2024-01, with the labels that each got.

#96 [TEST] MySQL 테스트 환경 구축
  .github/workflows/ci.yml
  build.gradle
  src/main/resources/application-ci.yml
  src/main/resources/application.yaml
  src/test/java/com/sports/server/support/isolation/DatabaseManager.java
Labels: 동규, test

#97 [CHORE] Rest Docs 의존성 추가 및 세팅 #94
  build.gradle
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/command/game/presentation/GameController.java
  src/main/java/com/sports/server/query/application/CheerTalkQueryService.java
  src/main/java/com/sports/server/query/dto/response/CheerTalkResponse.java
  src/main/java/com/sports/server/query/presentation/CheerTalkEventHandler.java
  src/main/java/com/sports/server/query/presentation/CheerTalkQueryController.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/cheertalk/presentation/CheerTalkControllerTest.java
  src/test/java/com/sports/server/command/game/presentation/GameControllerTest.java
  src/test/java/com/sports/server/command/report/presentation/ReportControllerTest.java
  src/test/java/com/sports/server/query/acceptance/CheerTalkEventHandlerTest.java
  src/test/java/com/sports/server/query/acceptance/CheerTalkQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/application/CheerTalkQueryServiceTest.java
  src/test/java/com/sports/server/query/presentation/CheerTalkQueryControllerTest.java
  src/test/java/com/sports/server/query/presentation/GameQueryControllerTest.java
  src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
  src/test/java/com/sports/server/query/presentation/TimelineQueryControllerTest.java
  src/test/java/com/sports/server/support/AcceptanceTest.java
  src/test/java/com/sports/server/support/DocumentationTest.java
Labels: 🐈 승희, chore, 동규

#98 MAIN 배포
  .github/workflows/cd.yml
  src/main/java/com/sports/server/common/log/LogFilter.java
  src/main/java/com/sports/server/query/repository/GameTeamQueryRepository.java
Labels: chore, 동규, db, fix
