Repository hufscheer/spectator-server, pull requests merged in 2024-02, with the labels that each got.

#101 [REFACTOR] 게임 목록 조회 커서 페이징 쿼리 개선 #100
  src/main/java/com/sports/server/query/repository/GamesQueryConditionMapper.java
Labels: refactor, db

#104 [REFACTOR] 기획 의도에 맞게 erd 수정
  src/main/java/com/sports/server/command/game/domain/LineupPlayer.java
  src/main/java/com/sports/server/command/leagueteam/LeagueTeamPlayer.java
  src/main/java/com/sports/server/command/record/domain/Record.java
  src/main/java/com/sports/server/command/record/domain/RecordType.java
  src/main/java/com/sports/server/command/record/domain/ReplacementRecord.java
  src/main/java/com/sports/server/command/record/domain/ScoreRecord.java
  src/main/java/com/sports/server/query/application/TimelineQueryService.java
  src/main/java/com/sports/server/query/dto/response/TimelineResponse.java
  src/main/java/com/sports/server/query/repository/RecordQueryRepository.java
  src/main/resources/db/migration/V6__update-timeline-lineup.sql
  src/test/java/com/sports/server/query/acceptance/LineupPlayerQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/acceptance/TimelineQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/presentation/TimelineQueryControllerTest.java
  src/test/resources/game-fixture.sql
  src/test/resources/record-fixture.sql
Labels: 🐈 승희, refactor

#105 [FEAT] 스포츠 전체 조회 기능 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/query/application/SportQueryService.java
  src/main/java/com/sports/server/query/dto/response/SportResponse.java
  src/main/java/com/sports/server/query/presentation/SportQueryController.java
  src/main/java/com/sports/server/query/repository/SportQueryRepository.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/cheertalk/presentation/CheerTalkControllerTest.java
  src/test/java/com/sports/server/command/game/presentation/GameControllerTest.java
  src/test/java/com/sports/server/command/report/presentation/ReportControllerTest.java
  src/test/java/com/sports/server/query/acceptance/SportQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/presentation/CheerTalkQueryControllerTest.java
  src/test/java/com/sports/server/query/presentation/GameQueryControllerTest.java
  src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
  src/test/java/com/sports/server/query/presentation/SportQueryControllerTest.java
  src/test/java/com/sports/server/query/presentation/TimelineQueryControllerTest.java
  src/test/java/com/sports/server/support/DocumentationTest.java
  src/test/java/com/sports/server/support/RestDocsConfig.java
Labels: feature, 🐈 승희

#111 [FEAT] 리그 조회 시 연도 별 필터링 기능 추가
  .github/workflows/ci.yml
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/command/league/domain/League.java
  src/main/java/com/sports/server/query/application/LeagueQueryService.java
  src/main/java/com/sports/server/query/dto/response/LeagueResponse.java
  src/main/java/com/sports/server/query/presentation/LeagueQueryController.java
  src/main/java/com/sports/server/query/repository/LeagueQueryDynamicRepository.java
  src/main/java/com/sports/server/query/repository/LeagueQueryDynamicRepositoryImpl.java
  src/main/java/com/sports/server/query/repository/LeagueQueryRepository.java
  src/main/resources/db/migration/V7__league-round.sql
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/query/acceptance/LeagueQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
  src/test/resources/league-fixture.sql
Labels: feature, refactor

#110 [FEAT] 라인업 조회 시 주장 정보 포함하도록 수정
  src/main/java/com/sports/server/query/dto/response/LineupPlayerResponse.java
  src/main/java/com/sports/server/query/repository/LineupPlayerQueryRepository.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/query/acceptance/GameQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/acceptance/LineupPlayerQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/presentation/GameQueryControllerTest.java
  src/test/resources/game-fixture.sql
Labels: feature, 🐈 승희

#114 [FEAT] 리그 조회 시 진행 중 여부 추가
  src/main/java/com/sports/server/query/application/InProgressLeagueChecker.java
  src/main/java/com/sports/server/query/dto/response/LeagueResponse.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/query/application/InProgressLeagueCheckerTest.java
  src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
Labels: feature, refactor, 동규

#115 [FEAT] 리그팀 전체 조회 기능 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/query/application/LeagueQueryService.java
  src/main/java/com/sports/server/query/dto/response/LeagueTeamResponse.java
  src/main/java/com/sports/server/query/presentation/LeagueQueryController.java
  src/main/java/com/sports/server/query/repository/LeagueTeamQueryRepository.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/query/acceptance/LeagueQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
  src/test/resources/league-fixture.sql
Labels: feature, 🐈 승희

#116 [FEAT] 타임라인 선수 교체 정보 관련 기능 추가
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/query/application/TimelineQueryService.java
  src/main/java/com/sports/server/query/application/timeline/RecordQueryService.java
  src/main/java/com/sports/server/query/application/timeline/ReplacementRecordQueryService.java
  src/main/java/com/sports/server/query/application/timeline/ScoreHistory.java
  src/main/java/com/sports/server/query/application/timeline/ScoreRecordQueryService.java
  src/main/java/com/sports/server/query/application/timeline/ScoreSnapshot.java
  src/main/java/com/sports/server/query/application/timeline/TimelineQueryService.java
  src/main/java/com/sports/server/query/dto/mapper/RecordMapper.java
  src/main/java/com/sports/server/query/dto/response/RecordResponse.java
  src/main/java/com/sports/server/query/dto/response/ReplacementRecordResponse.java
  src/main/java/com/sports/server/query/dto/response/ScoreRecordResponse.java
  src/main/java/com/sports/server/query/dto/response/TimelineResponse.java
  src/main/java/com/sports/server/query/presentation/TimelineQueryController.java
  src/main/java/com/sports/server/query/repository/GameTeamQueryRepository.java
  src/main/java/com/sports/server/query/repository/RecordQueryRepository.java
  src/main/java/com/sports/server/query/repository/ReplacementRecordQueryRepository.java
  src/main/java/com/sports/server/query/repository/ScoreRecordQueryRepository.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/query/acceptance/TimelineQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/presentation/TimelineQueryControllerTest.java
  src/test/java/com/sports/server/support/DocumentationTest.java
  src/test/resources/record-fixture.sql
Labels: feature, refactor, 동규
