Repository hufscheer/spectator-server, pull requests merged in 2025-08, with the labels that each got.

#348 [FEATURE] 팀 상세조회에 승무패, 득점왕, 트로피 응답 추가 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/command/game/application/GameService.java
  src/main/java/com/sports/server/command/game/domain/GameTeamRepository.java
  src/main/java/com/sports/server/command/game/exception/GameErrorMessages.java
  src/main/java/com/sports/server/command/league/domain/LeagueStatisticsRepository.java
  src/main/java/com/sports/server/command/league/domain/LeagueTeamRepository.java
  src/main/java/com/sports/server/command/team/domain/PlayerGoalCountWithRank.java
  src/main/java/com/sports/server/command/team/domain/Unit.java
  src/main/java/com/sports/server/command/team/exception/TeamErrorMessages.java
  src/main/java/com/sports/server/query/application/GameQueryService.java
  src/main/java/com/sports/server/query/application/LeagueQueryService.java
  src/main/java/com/sports/server/query/application/TeamQueryService.java
  src/main/java/com/sports/server/query/dto/request/GamesQueryRequestDto.java
  src/main/java/com/sports/server/query/dto/response/TeamDetailResponse.java
  src/main/java/com/sports/server/query/presentation/TeamQueryController.java
  src/main/java/com/sports/server/query/repository/GameTeamDynamicRepository.java
  src/main/java/com/sports/server/query/repository/GamesQueryConditionMapper.java
  src/main/java/com/sports/server/query/repository/TeamDynamicRepository.java
  src/main/java/com/sports/server/query/repository/TeamQueryDynamicRepository.java
  src/main/java/com/sports/server/query/repository/TeamQueryDynamicRepositoryImpl.java
  src/main/java/com/sports/server/query/repository/TimelineQueryRepository.java
  src/main/java/com/sports/server/query/support/PlayerInfoProvider.java
  src/main/resources/db/migration/dev/T2__alter_player_student_number_to_nullable.sql
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/team/presentation/TeamControllerTest.java
  src/test/java/com/sports/server/query/acceptance/GameQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/acceptance/LeagueQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/acceptance/LeagueTeamQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/acceptance/PlayerQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/application/GameLeagueTeamQueryServiceTest.java
  src/test/java/com/sports/server/query/application/GameQueryServiceTest.java
  src/test/java/com/sports/server/query/application/LineupPlayerQueryServiceTest.java
  src/test/java/com/sports/server/query/application/TeamQueryServiceTest.java
  src/test/java/com/sports/server/query/presentation/GameQueryControllerTest.java
  src/test/java/com/sports/server/query/presentation/TeamQueryControllerTest.java
  src/test/java/com/sports/server/support/ServiceTest.java
  src/test/resources/game-fixture.sql
  src/test/resources/league-fixture.sql
  src/test/resources/timeline-fixture.sql
Labels: feature, 5차 릴리즈

#355 [FEATURE] '이전 리그'에 필요한 리그 통계, 득점왕 구현
  src/main/java/com/sports/server/command/game/application/GameStatusScheduler.java
  src/main/java/com/sports/server/command/league/application/LeagueStatisticsService.java
  src/main/java/com/sports/server/command/league/application/LeagueTopScorerService.java
  src/main/java/com/sports/server/command/league/domain/LeagueTeamRepository.java
  src/main/java/com/sports/server/command/league/domain/LeagueTopScorerRepository.java
  src/main/java/com/sports/server/query/application/LeagueQueryService.java
  src/main/java/com/sports/server/query/dto/response/LeagueStatisticsResponse.java
  src/main/java/com/sports/server/query/dto/response/LeagueTeamResponse.java
  src/main/java/com/sports/server/query/dto/response/LeagueTopScorerResponse.java
  src/main/java/com/sports/server/query/presentation/LeagueQueryController.java
  src/main/java/com/sports/server/query/repository/TimelineQueryRepository.java
  src/main/java/com/sports/server/query/support/PlayerInfoProvider.java
  src/test/java/com/sports/server/command/league/application/LeagueStatisticsServiceTest.java
  src/test/java/com/sports/server/command/league/application/LeagueTopScorerServiceTest.java
  src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
  src/test/resources/league-fixture.sql
Labels: 5차 릴리즈

#357 [TEST] 팀 쿼리 테스트 코드 추가 및 리그 통계 버그 해결
  src/docs/asciidoc/api.adoc
  src/main/java/com/sports/server/command/game/application/GameStatusScheduler.java
  src/main/java/com/sports/server/command/league/application/LeagueStatisticsService.java
  src/main/resources/static/docs/api.html
  src/test/java/com/sports/server/command/league/application/LeagueStatisticsServiceTest.java
  src/test/java/com/sports/server/query/acceptance/CheerTalkQueryAcceptanceTest.java
  src/test/java/com/sports/server/query/application/CheerTalkQueryServiceTest.java
  src/test/java/com/sports/server/query/application/TeamQueryServiceTest.java
  src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
  src/test/resources/cheer-talk-fixture.sql
  src/test/resources/team-query-fixture.sql
Labels: fix, test, 5차 릴리즈
